---
title: "Flowering Analysis"
author: "Emma Chandler"
date: "3/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
remove(list = ls())
```

Load Libraries
```{r}
library(ggplot2)
library(lmerTest)

```

Load Data
```{r}
flower <- read.csv("~/horsenettle_2022/data/Flowering_2.csv", na.strings=c("", "NA"), header = TRUE)

```

# Creating a figure theme for all plots
```{r}
HStheme <- function(){            
  theme_bw()+                          
  theme(axis.text.x = element_text(size = 12), 
        text = element_text(family = "sans"), 
        axis.text.y = element_text(size = 12),
        plot.subtitle = element_text(size = 16, vjust = 1, hjust = 0.5),
        axis.title = element_text(size = 14),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
        legend.text = element_text(size = 12),
        legend.title = element_blank())
}
```

Visualize Data
```{r}
# First Flower
firstFlower.m <- lmer(DOY_flower1 ~ Region + Population + (1|Population:ID), data = flower)

(firstFlower.m.a <- anova(firstFlower.m))
(firstFlower.m.r <- ranova(firstFlower.m))


ggplot(flower, aes(x = Region, y = DOY_flower1, fill = Region)) +
  geom_boxplot(alpha = 0.8) +
  labs(y = "Day after Growth Initiation")+
  scale_fill_manual(values = c("#104E8B", "#CD2626")) +
  # geom_jitter(width = 0.25) +
  HStheme()

# Saving graph
ggsave("figures/firstFlower.png", width = 7, height = 5, dpi = 300)

t.test(DOY_flower1 ~ Region, flower)


# Second Flower
ggplot(flower, aes(x = Treatment, y = DOY_flower2, fill = Treatment)) +
  geom_boxplot(alpha = 0.8) +
  labs(y = "Day after Growth Initiation", title = "First Flower in Treatment")+
  scale_fill_manual(values = c("#474747", "#FF3030")) +
  # geom_jitter(width = 0.25) +
  HStheme()

# Saving graph
# ggsave("figures/secondFlower.png", width = 7, height = 5, dpi = 300)


# Flower Type
# Chi-squared test
F.North <- flower %>% filter(Region == "North")
chisq.test(y = F.North$Flower_Type, x = F.North$Treatment)



bar_dat <- flower[-which(flower$Flower_Type == ""), ]

ggplot(bar_dat, aes(x = Flower_Type, fill = Treatment)) +
  geom_bar(alpha = 0.8) +
  facet_wrap(~ Region, strip.position = "top")+
  labs(x = "Flower Type", y = "Count") +
  scale_fill_manual(values = c("#474747", "#FF3030"))+
  HStheme() +
  theme(strip.placement = "outside")

# Saving graph
ggsave("figures/flowerType.png", width = 7, height = 5, dpi = 300)


```

Flower counts
```{r}

Flower2 <- flower %>%
  mutate(Flowered_1 = if_else(FirstFlower == "", 0,1)) %>% 
  mutate(Flowered_2 = if_else(SecondFlower == "", 0,1)) 

FirstFlower <- Flower2 %>% 
  group_by(Treatment, Region) %>% 
  summarise(Sum = sum(Flowered_1)) %>% 
  mutate(Flower = "Before")

SecondFlower <- Flower2 %>% 
  group_by(Treatment, Region) %>% 
  summarise(Sum = sum(Flowered_2)) %>% 
  mutate(Flower = "After") 

Flower3 <- rbind(FirstFlower, SecondFlower)
Flower3$Flower <- factor(Flower3$Flower, levels = c("Before","After"))

ggplot(Flower3, aes(x = Flower, y = Sum, fill = Treatment)) +
  geom_col(position = position_dodge(), alpha = 0.8) +
  facet_wrap(~Region, strip.position = "top") +
  HStheme() +
  scale_fill_manual(values = c("#474747", "#FF3030"))+
  labs(x = "Treatment Placement", y = "Genets that Flowered") +
  theme(strip.placement = "outside")

# Saving graph
ggsave("figures/FlowerCounts.png", width = 7, height = 5, dpi = 300)  

```

