---
title: "Morphology Analysis"
author: "Emma Chandler"
date: "3/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
remove(list = ls())
```

Load Libraries

```{r message=FALSE}
library(ggplot2)
library(lmerTest)
library(lme4)
library(dplyr)
library(reshape2)
library(ggpubr)
library(memisc)
library(forcats)
library(car)
```

Load Data

```{r}
morph <- read.csv("~/horsenettle_2022/data/flower_traits.csv", header = TRUE)
```

# Creating a figure theme for all plots

```{r}
HStheme <- function(){            
  theme_bw()+                          
  theme(axis.text.x = element_text(size = 12), 
        text = element_text(family = "sans"), 
        axis.text.y = element_text(size = 12),
        plot.subtitle = element_text(size = 16, vjust = 1, hjust = 0.5),
        axis.title = element_text(size = 12),
        strip.text.x = element_text(size = 12),
        strip.text.y = element_text(size = 12),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
        legend.text = element_text(size = 12),
        legend.title = element_blank())
}
```

Sample Size

```{r}

(sampsize <- morph %>%
  filter(Treatment == "Heat") %>% 
  na.omit() %>% 
  group_by(Region) %>% 
  summarize(count = n_distinct(Iden)))

```

Pistil Length

```{r}
pistil.m <- lmer(style_length ~ Treatment*Region + (1|ID), data = morph)

Anova(pistil.m)
anova(pistil.m, type = 2)
summary(pistil.m)  
# write.csv(summary(pistil.m)$coefficients, file = "output/pistilLength_results.csv" )


# Style Length
ggplot(morph, aes(x = Treatment, y = style_length, fill = Treatment)) +
  geom_violin(alpha = 0.2) +
  geom_boxplot(width=0.1) +
  # geom_jitter(alpha = 0.4, position=position_jitter(0.2)) +
  facet_wrap(~ Region) +
  labs(y = "Stigma + Style Length (mm)")+
  scale_fill_manual(values = c("#104E8B", "#CD2626")) +
  HStheme() +
  theme(legend.position = "none")

# Dot plot
(dot_plot <- ggerrorplot(morph, x = "Treatment", y = "style_length", desc_stat = "mean_se", color = "Region") +
  theme_classic() +
  labs(x = "Treatment", y = "Style + Stigma Length (mm)")+
  scale_colour_manual(values = c("#104E8B", "#CD2626")) +
  theme(text = element_text(family = "sans"),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title = element_text(size = 12),
        plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        legend.text = element_text(size = 12),
        legend.title = element_blank()))

# Saving graph
# ggsave("figures/StyleLength_1.png", width = 7, height = 5, dpi = 300)


# Is there phenotypic plasticity
ggplot(morph, aes(x = Treatment, y = style_length, color = Region)) +
  HStheme() +
  stat_summary(aes(group = Region), fun = mean, geom = "line", size = 1, alpha = 0.7) +
  stat_summary(aes(group = Region), 
               geom = "errorbar",
               fun.data = mean_cl_boot,
               width = 0.1,size = 0.2) +
  # geom_jitter(width = 0.22) +
  labs(y = "Style + Stigma Length (mm)") +
  scale_color_manual(values = c("#104E8B", "#CD2626")) 
  

# Saving graph
# ggsave("figures/styleLength_2.png", width = 7, height = 5, dpi = 300)

```

Stamen Length

```{r}

stamen.m <- lmer(stamen_length ~ Treatment*Region + (1|ID), data = morph)

Anova(stamen.m)
summary(stamen.m) 
# write.csv(summary(stamen.m)$coefficients, file = "output/StamenLength_results.csv" )

# Style Length
ggplot(morph, aes(x = Treatment, y = stamen_length, fill = Treatment)) +
  geom_violin(alpha = 0.2) +
  geom_boxplot(width=0.1) +
  # geom_jitter(alpha = 0.4, position=position_jitter(0.2)) +
  facet_wrap(~ Region) +
  labs(y = "Stamen Length (mm)")+
  scale_fill_manual(values = c("#104E8B", "#CD2626")) +
  HStheme() +
  theme(legend.position = "none")

# Saving graph
# ggsave("figures/StamenLenght_1.png", width = 7, height = 5, dpi = 300)


# Is there phenotypic plasticity
ggplot(morph, aes(x = Treatment, y = stamen_length, color = Region)) +
  HStheme() +
  stat_summary(aes(group = Region), fun = mean, geom = "line", size = 1, alpha = 0.7) +
  stat_summary(aes(group = Region), 
               geom = "errorbar",
               fun.data = mean_cl_boot,
               width = 0.1, size = 0.2) +
  labs(y = "Stamen Length (mm)") +
  scale_color_manual(values = c("#104E8B", "#CD2626")) 
  

# Saving graph
# ggsave("figures/StamenLength_2.png", width = 7, height = 5, dpi = 300)


```

Ovule Number

```{r}
# Difference between North and South for control
ovule.m <- glmer(ovule_number ~ Treatment * Region + (1|ID), data = morph, family = "poisson")

Anova(ovule.m)
summary(ovule.m) 

# write.csv(summary(ovule.m)$coefficients, file = "output/OvuleLength_results.csv" )

morph %>% 
  group_by(Treatment) %>% 
  filter(!is.na(ovule_number)) %>% 
  summarise(mean(ovule_number))
  


# Style Length
ggplot(morph, aes(x = Treatment, y = ovule_number, fill = Treatment)) +
  geom_violin(alpha = 0.2) +
  geom_boxplot(width=0.1) +
  # geom_jitter(alpha = 0.4, position=position_jitter(0.2)) +
  facet_wrap(~ Region) +
  labs(y = "Ovule Number")+
  scale_fill_manual(values = c("#104E8B", "#CD2626")) +
  HStheme() +
  theme(legend.position = "none")

# Saving graph
# ggsave("figures/OvuleNumber_1.png", width = 7, height = 5, dpi = 300)


# Is there phenotypic plasticity
ggplot(morph, aes(x = Treatment, y = ovule_number, color = Region)) +
  HStheme() +
  stat_summary(aes(group = Region), fun = mean, geom = "line", size = 1, alpha = 0.7) +
  stat_summary(aes(group = Region), 
               geom = "errorbar",
               fun.data = mean_cl_boot,
               width = 0.1, size = 0.2) +
  labs(y = "Ovule Number") +
  scale_color_manual(values = c("#104E8B", "#CD2626")) 
  

# Saving graph
# ggsave("figures/OvuleNumber2.png", width = 7, height = 5, dpi = 300)

```

## Stacked Figures

```{r}
Reg_cont <- melt(subset(Control, select=c(Region, style_length, stamen_length)), id.var="Region")

lables <- c(style_length = "Style + Stigma Length", stamen_length = "Anther Length")
  


(All.spor.reg <- ggplot(Reg_cont, aes(Region, value, fill = Region)) + 
    geom_boxplot(alpha = 0.8) +
    facet_wrap(variable ~ ., scales = "free_y", ncol = 2,
               labeller = labeller(variable = lables)) +
    scale_fill_manual(values = c("#104E8B", "#CD2626")) +
    HStheme() +
    labs(x = "Region", y = "Length (mm)")) +
    theme(legend.position = "none")

# Saving graph
# ggsave("figures/SS_regional.png", width = 7, height = 5, dpi = 300)


trt <- melt(subset(morph, select=c(Treatment, style_length, stamen_length)), id.var="Treatment")

lables <- c(style_length = "Style + Stigma Length", stamen_length = "Anther Length")
  

# Box plot
(All.spor.reg <- ggplot(trt, aes(Treatment, value, fill = Treatment)) + 
    geom_boxplot(alpha = 0.8) +
    facet_wrap(variable ~ ., scales = "free_y", ncol = 2,
               labeller = labeller(variable = lables)) +
    scale_fill_manual(values = c("#474747", "#FF3030")) +
    HStheme() +
    labs(x = "Treatment", y = "Length (mm)")) +
    theme(legend.position = "none")


# Dot plot
trt$Treatment <- ordered(trt$Treatment, levels = c("Control", "Heat"))

(dot_plot <- ggerrorplot(trt, x = "Treatment", y = "value",  desc_stat = "mean_se", color = "Treatment") +
  theme_classic() +
  labs(x = "Treatment", y = "Length (mm)")+
  scale_colour_manual(values = c("#5E5E5E", "#EE0000")) +
  facet_wrap(variable ~ ., scales = "free_y", ncol = 2,
               labeller = labeller(variable = lables)) +
  theme(text = element_text(family = "sans"),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title = element_text(size = 12),
        plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        legend.text = element_text(size = 12),
        legend.title = element_blank()))


# Saving graph
# ggsave("figures/SS_trt.png", width = 7, height = 5, dpi = 300)

```

## Stamen to Style length ratios

```{r}

Iden_Mean <- morph %>% 
  group_by(Iden, Block, Region, Treatment, Population) %>% 
  summarise(across(style_length:unfertilized_ovules, mean)) %>% 
  mutate(style.stamen = style_length/stamen_length)

Ratio <- lm(style.stamen ~ Treatment + Region, data = Iden_Mean)

plot(Ratio)
Anova(Ratio)


bartlett.test(style.stamen ~ Treatment, data = Iden_Mean)


ggplot(Iden_Mean, aes(x = Treatment, y = style.stamen, fill = Treatment)) +
  geom_boxplot(alpha = 0.8) +
  labs(y = "Style + Stigma : Anther Length Ratio")+
  scale_fill_manual(values = c("#474747", "#FF3030")) +
  HStheme() +
  theme(legend.position = "none")

# Saving graph
ggsave("figures/StyleStamenRatio.png", width = 7, height = 5, dpi = 300)


# Correlations for treatment groups of style and stamen
CorCont <- Iden_Mean %>% 
  filter(Treatment == "Control")

cor.test(x = CorCont$style_length, y = CorCont$stamen_length, method = "pearson")


CorHeat <- Iden_Mean %>% 
  filter(Treatment == "Heat")

cor.test(x = CorHeat$style_length, y = CorHeat$stamen_length, method = "pearson")



ggplot(Iden_Mean, aes(x = style_length, y = stamen_length, color = Treatment)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  HStheme() +
  scale_color_manual(values = c("#474747", "#FF3030")) +
  labs(x = "Mean Style + Stigma Length (mm)", y = "Mean Anther Length (mm)")


# Saving graph
ggsave("figures/StyleStamenCor.png", width = 7, height = 5, dpi = 300)


# Is there phenotypic plasticity

morph_sss <- morph %>% 
  group_by(Iden, Block, Treatment, Population, Region) %>% 
  summarise(across(style_length:unfertilized_ovules, mean)) %>% 
  mutate(style.stamen = style_length/stamen_length)

ggplot(morph_sss, aes(x = Treatment, y = style.stamen, color = Region)) +
  HStheme() +
  stat_summary(aes(group = Region), fun = mean, geom = "line", size = 1, alpha = 0.7) +
  stat_summary(aes(group = Region), 
               geom = "errorbar",
               fun.data = mean_cl_boot,
               width = 0.1,size = 0.2) +
  geom_jitter(width = 0.22) +
  labs(y = "Style + Stigma Length (mm)") +
  scale_color_manual(values = c("#104E8B", "#CD2626")) 

# Saving graph
# ggsave("figures/StyleStamenRatio_pp_dot.png", width = 7, height = 5, dpi = 300)

```
