---
title: "Fruit and Seeds"
author: "Emma Chandler"
date: "5/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
remove(list = ls())
```

Load Libraries
```{r message=FALSE}
library(ggplot2)
library(lmerTest)
library(lme4)
library(dplyr)
library(reshape2)
library(tidyr)
library(car)
library(emmeans)
```

Load Data
```{r}
morph <- read.csv("~/horsenettle_2022/data/flower_traits.csv", header = TRUE)
fruit <- read.csv("~/horsenettle_2022/data/fruit.csv", header = TRUE)

```

# Creating a figure theme for all plots
```{r}
HStheme <- function(){            
  theme_bw()+                          
  theme(axis.text.x = element_text(size = 12), 
        text = element_text(family = "sans"), 
        axis.text.y = element_text(size = 12),
        plot.subtitle = element_text(size = 16, vjust = 1, hjust = 0.5),
        axis.title = element_text(size = 14),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
        legend.text = element_text(size = 12),
        legend.title = element_blank())
}
```



Fruit Set
```{r}

# Calculating fruit set and rounding to 3 digits
fruit$fruit_set <- fruit$fruit_count / fruit$flowers_pollinated
fruit$fruit_set <- round(fruit$fruit_set, digits = 3)


# Chi-squared test
F.North <- fruit %>% filter(Region == "North")
chisq.test(y = F.North$fruit_set, x = F.North$Treatment)


# Plots
fruit_bar <- F.North
fruit_bar$fruit_set <- as.character(fruit_bar$fruit_set)

(fruit_bar %>% 
  na.omit() %>% 
  ggplot() + 
    geom_bar(aes(x = fruit_set, fill = Treatment), alpha = 0.8)+ 
    labs(x = "Fruit Set", y = "Count") +
    scale_fill_manual(values = c("#7AC5CD", "#FF6A6A")) + 
    HStheme())

# Saving graph
# ggsave("figures/FruitSet.png", width = 7, height = 5, dpi = 300)

```



Add temporal block
```{r}
# Make a temporal block variable
morph <- morph %>% mutate(Block_2 = case_when(Block == "A" ~ "Jan",
                                            Block == "B" ~ "Jan",
                                            Block == "C" ~ "Jun",
                                            Block == "D" ~ "Jun"))
```



## Seed per fruit
```{r}
# Mixed Effects Linear Model for Viable Seed
seed.m <- glmer(viable_seed ~ Treatment * Region + Block_2 + Population + (1|ID), data = morph, family = "poisson")

library(DHARMa)
testOverdispersion(seed.m)

Anova(seed.m)
summary(seed.m)  
# write.csv(summary(seed.m)$coefficients, file = "output/ViableSeeds_results.csv" )



(morph %>% 
  group_by(Treatment) %>% 
  dplyr::summarize(mean = mean(viable_seed, na.rm = TRUE)))


ggplot(morph, aes(x = Treatment, y = viable_seed, fill = Treatment)) +
  geom_boxplot() +
  labs(y = "Viable Seeds per Fruit")+
  scale_fill_manual(values = c("#7AC5CD", "#FF6A6A")) +
  facet_wrap(~Region) +
  HStheme() +
  theme(legend.position = "none")

# Saving graph
# ggsave("figures/ViableSeeds.png", width = 7, height = 5, dpi = 300)
```


```{r}
# Mixed effects model for unfertilized ovules
uf.m <- glmer(unfertilized_ovules ~ Treatment * Region + Block_2 + Population + (1|ID), data = morph, family = "poisson")

# Test for overdispersion
testOverdispersion(uf.m)

Anova(uf.m)
summary(uf.m)  
# write.csv(summary(uf.m)$coefficients, file = "output/UnfertilizedOvules_results.csv" )

# Post hoc test for significant interactions
emmeans(uf.m, specs=pairwise ~ Treatment*Region, adjust="tukey")

(morph %>% 
  group_by(Treatment) %>% 
  dplyr::summarize(mean = mean(unfertilized_ovules, na.rm = TRUE)))
```


```{r}
# Linear model for aborted seeds
abort.m <- glmer(aborted_seed ~ Treatment * Region + Block_2 + Population + (1|ID), data = morph, family = "poisson")

# Test for overdispersion
testOverdispersion(abort.m)

Anova(abort.m)
summary(abort.m) 
# write.csv(summary(abort.m)$coefficients, file = "output/AbortedSeeds_results.csv" )

# Post hoc test for significant interactions
emmeans(abort.m, specs=pairwise ~ Treatment*Region, adjust="tukey")

(morph %>% 
  group_by(Treatment) %>% 
  dplyr::summarize(mean = mean(aborted_seed, na.rm = TRUE)))


# Plot all viable seeds, unfertilized ovules, and aborted seeds together
long_seed <- morph %>% 
  gather(seed_type, count, viable_seed:unfertilized_ovules, factor_key = TRUE) %>% 
  mutate(seed_type2 = case_when(seed_type == "viable_seed" ~ "Viable Seed",
                                seed_type == "aborted_seed" ~ "Aborted Seed",
                                seed_type == "unfertilized_ovules" ~ "Unfertilized Ovule"))


long_seed$seed_type2 <- factor(long_seed$seed_type2, c("Unfertilized Ovule", "Aborted Seed", "Viable Seed"))

ggplot(long_seed, aes(x = seed_type2, y = count, fill = Treatment)) +
  geom_boxplot() +
  labs(y = "Count per fruit", x = "Ovule Fate")+
  scale_fill_manual(values = c("#7AC5CD", "#FF6A6A")) +
  HStheme() 

# Saving graph
# ggsave("figures/seed_type.png", width = 7, height = 5, dpi = 300)


```

