---
title: "Stacked Phenotypic Plasticity Figures"
author: "Emma Chandler"
date: "6/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Load Libraries
```{r}
library(ggplot2)
library(dplyr)
library(reshape2)
library(ggpubr)
```

Load Data
```{r}
remove(list = ls())

morph <- read.csv("~/horsenettle_2022/data/flower_traits.csv", header = TRUE)
Germ <- read.csv("~/horsenettle_2022/data/PollenGerm.csv", header = TRUE)
Pdiam <- read.csv("~/horsenettle_2022/data/PollenDiameter.csv", header = TRUE)


```

Figure Theme
```{r}
HStheme <- function(){            
  theme_bw()+                          
  theme(axis.text.x = element_text(size = 12), 
        text = element_text(family = "sans"), 
        axis.text.y = element_text(size = 12),
        plot.subtitle = element_text(size = 16, vjust = 1, hjust = 0.5),
        axis.title = element_text(size = 14),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
        legend.text = element_text(size = 12),
        legend.title = element_blank())
}
```


Combine data frames
```{r}

# Calculate pollen germination
Germ$germ <- Germ$tubes / Germ$total_grains

# Summarize variables with three flowers to one mean
morph <- morph %>% 
  group_by(Region, Population, Iden, Treatment) %>% 
  summarise(style_length = mean(style_length),
            stamen_length = mean(stamen_length),
            ovule_number = mean(ovule_number),
            viable_seed = mean(viable_seed),
            aborted_seed = mean(aborted_seed),
            unfertilized_ovules = mean(unfertilized_ovules))

# Only keep important columns
Pdiam <- Pdiam[c(2,3, 5, 7)]
Germ <- Germ[c(2,5,7,12)]


Pollen <- merge(Germ, Pdiam, by = c("Iden", "Treatment", "Region"), all.x = TRUE, all = TRUE)

All <- merge(Pollen, morph, by = c("Iden", "Region", "Treatment"), all.x = FALSE, all = TRUE)

```



Stacked Figure
```{r}
meltedDat <- melt(subset(All, select = c(Region, Treatment, style_length, stamen_length, PD_mean, ovule_number, germ, viable_seed, unfertilized_ovules, aborted_seed)), id.var= c("Region", "Treatment"))

lables <- c(style_length = "Female Structure (mm)", stamen_length = "Male Structure (mm)",  PD_mean = "Mean Pollen Diameter (µm)", ovule_number = "Ovule Count", germ = "Pollen Germination", unfertilized_ovules = "Unfertilized Ovules", viable_seed = "Viable Seed Count", aborted_seed = "Aborted Seed Count")
  
# Plots of variables with significant treatment effects
meltedDat$Treatment <- ordered(meltedDat$Treatment, levels = c("Control", "Heat"))

(plot1 <- ggerrorplot(meltedDat, x = "Treatment", y = "value",  desc_stat = "mean_se", color = "Treatment") +
  theme_classic() +
  labs(x = "Treatment", y = "")+
  scale_colour_manual(values = c("#5E5E5E", "#EE0000")) +
  facet_wrap(variable ~ ., scales = "free_y", ncol = 4,
               labeller = labeller(variable = lables)) +
  theme(text = element_text(family = "sans"),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title = element_text(size = 12),
        strip.text = element_text(size = 12),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        legend.text = element_text(size = 12),
        legend.title = element_blank(),
        legend.position = "bottom", 
        legend.justification = "center"))



# Saving graph
ggsave("figures/StackedDotPlot.png", width = 11, height = 6.5, dpi = 300)
```



Phenotypic Plasticity
```{r}
meltedDat2 <- melt(subset(All, select = c(Region, Treatment, style_length, stamen_length, PD_mean, ovule_number, germ, unfertilized_ovules, aborted_seed, viable_seed)), id.var= c("Region", "Treatment"))

lables2 <- c(style_length = "Female Structure (mm)", stamen_length = "Male Structure (mm)", PD_mean = "Mean Pollen Diameter (µm)", ovule_number = "Ovule Count", germ = "Pollen Germination", unfertilized_ovules = "Unfertilized Ovule Count", aborted_seed = "Aborted Seed Count", viable_seed = "Viable Seed Count")


# Is there phenotypic plasticity
ggplot(meltedDat2, aes(x = Treatment, y = value, color = Region)) +
  theme_classic() +
  stat_summary(aes(group = Region), fun = mean, geom = "line", size = 1, alpha = 0.7) +
  facet_wrap(variable ~ ., scales = "free_y", ncol = 4,
               labeller = labeller(variable = lables2)) +
  stat_summary(aes(group = Region), 
               geom = "errorbar",
               fun.data = mean_cl_boot,
               width = 0.1,size = 0.2) +
  annotate("text", label = "label text")+
  labs(y = "") +
  scale_color_manual(values = c("#104E8B", "#CD2626")) +
  theme(text = element_text(family = "sans"),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title = element_text(size = 12),
        strip.text = element_text(size = 10),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        legend.text = element_text(size = 12),
        legend.title = element_blank(),
        legend.position = "bottom", 
        legend.justification = "center")
  

# Saving graph
ggsave("figures/StackedPP.png", width = 9.5, height = 5, dpi = 300)
```


Is there a correlation between the number of ovules and the number of unfertilized ovules
```{r}

cor.test(x = All$ovule_number, y = All$unfertilized_ovules, method = "pearson")

# Correlations for treatment groups of Ovule number and unfertilized ovules
CorCont <- All %>% 
  filter(Treatment == "Control")

cor.test(x = CorCont$ovule_number, y = CorCont$unfertilized_ovules, method = "pearson")


CorHeat <- All %>% 
  filter(Treatment == "Heat")

cor.test(x = CorHeat$ovule_number, y = CorHeat$unfertilized_ovules, method = "pearson")



ggplot(Iden_Mean, aes(x = style_length, y = stamen_length, color = Treatment)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  HStheme() +
  scale_color_manual(values = c("#474747", "#FF3030")) +
  labs(x = "Mean Style + Stigma Length (mm)", y = "Mean Anther Length (mm)")

```
