---
title: "MasterSpreadSheet"
author: "Emma Chandler"
date: '2022-08-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Libraries
```{r}
library(tidyr)
library(dplyr)
library(reshape2)
library(data.table)
```



# Load Data
```{r}
remove(list = ls())


HN2021 <- read.csv("~/horsenettle_2022/data/Horsenettle2021_data.csv", header = TRUE)

flower <- read.csv("~/horsenettle_2022/data/flower_traits.csv", header = TRUE)
fruit <- read.csv("~/horsenettle_2022/data/fruit.csv", header = TRUE)
Pdiam <- read.csv("~/horsenettle_2022/data/PollenDiameter.csv", header = TRUE)
Pgerm <- read.csv("~/horsenettle_2022/data/PollenGerm.csv", header = TRUE)
```

# Merge 2022 data
```{r}
# Convert flower to wide data
flower_w <- dcast(melt(flower, id.vars = c("ID", "Iden", "Region", "Population", "Treatment", "Block", "Number")), Iden~variable+Number)

# Change column names in Pgerm
setnames(Pgerm, old = c('population', 'location', 'ramet'), new = c('Population', 'Region', 'Block'))

# Merge Datasets
flower_fruit <- merge(fruit, flower_w, by = "Iden", all = TRUE)

pollen <- merge(Pdiam, Pgerm, by = c("ID", "Iden", "Region", "Population", "Block", "Treatment"), all = TRUE)

HN2022 <- merge(flower_fruit, pollen, by = c("ID", "Iden", "Region", "Population", "Block", "Treatment"), all = TRUE)

```

# Clean 2021 Dataset to match 2022 dataset
```{r}

# Change column names in Pgerm
setnames(HN2021, old = c('population', 'location', 'ramet'), new = c('Population', 'Region', 'Block'))

```

# Merge data from 2021 and 2022
```{r}

HNall <- merge(HN2022, HN2021, by = c("ID", "Iden", "Region", "Population", "Block"), all = TRUE)

# write.csv(x = HNall, file = "~/horsenettle_2022/data/MasterSpreadsheet_HN2022_HN2021.csv")

```

